export const data = [
    {
        id:1,
        name:"Ram",
        email:"ram@gmail.com",
        address:"dhapahkhel",
        salary:50000,
        password:"rambahadurA@1",
        Phonenumber:9841232323
    },
    {
        id:2,
        name:"Shyam",
        email:"shyam@gmail.com",
        address:"laganhkhel",
        salary:40000,
        password:"shyambabuB@2",
        Phonenumber:9841434343
    },
    {
        id:3,
        name:"Hari",
        email:"hari@gmail.com",
        password:"haribabu@1",
        salary:60000,
        address:"jawalaahkhel",
        Phonenumber:98417777
    },
    {
        id:4,
        name:"Govinda",
        email:"govinda@gmail.com",
        address:"koteshor",
        password:"govindababurD@4",
        salary:70000,
        Phonenumber:98418888
    },
    {
        id:5,
        name:"Krishna",
        email:"krishna@gmail.com",
        address:"baneshor", 
        salary:80000,
        password:"krishnababuE@5",
        Phonenumber:984120000
    },
    {
        id:6,
        name:"Gaurav",
        email:"gaurav@gmail.com",
        address:"baneshor", 
        salary:80000,
        password:"gauravG@6",
        Phonenumber:98412989
    },
    {
        id:7,
        name:"Saurav",
        email:"saurav@gmail.com",
        address:"maitidevi", 
        salary:80000,
        password:"sauravS@7",
        Phonenumber:98412989
    },
    {
        id:8,
        name:"Sunil",
        email:"sunil@gmail.com",
        address:"maitidevi", 
        salary:80000,
        password:"sunilS@8",
        Phonenumber:98412989
    },
    {
        id:9,
        name:"Anil",
        email:"mnil@gmail.com",
        address:"maitidevi", 
        salary:90000,
        password:"AnilA@9",
        Phonenumber:98412989
    },
    
   


]